kafka:
  jaeger: false
  brokers: ["localhost:9092"]
  groupID: b2b
  initTopics: false
  SSL: false
  SslCaPem: string
  Username: user
  Password: password

consumers:
  usersUpdate:
    topicName: b2b.user.state
    partitions: 1
    replicationFactor: 1
  paymentInvoices:
    topicName: b2b.payment-invoices.create
    partitions: 1
    replicationFactor: 1
  resetUserLimits:
    topicName: b2b.users.reset-limit
    partitions: 1
    replicationFactor: 1
  resetDepartmentLimits:
    topicName: b2b.departments.reset-limit
    partitions: 1
    replicationFactor: 1
  updateBalanceInner:
    topicName: corporations_service.balance.update
    partitions: 1
    replicationFactor: 1

producers:
  balanceWatcher:
    topicName: corporations.user.balance
    partitions: 1
    replicationFactor: 1
  updateBalanceInner:
    topicName: corporations_service.balance.update
    partitions: 1
    replicationFactor: 1
