kafka:
  jaeger: false
  brokers: ["localhost:9092"]
  groupID: b2b
  initTopics: false
  SSL: false
  SslCaPem: string
  Username: user
  Password: password

producers:
  balanceWatcher:
    topicName: corporations.user.balance
    partitions: 1
    replicationFactor: 1
  updateBalanceInner:
    topicName: corporations_service.balance.update
    partitions: 1
    replicationFactor: 1
