// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: protoc/example/example.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name1 string `protobuf:"bytes,1,opt,name=name1,proto3" json:"name1,omitempty"`
	Name2 string `protobuf:"bytes,2,opt,name=name2,proto3" json:"name2,omitempty"`
	Name3 string `protobuf:"bytes,3,opt,name=name3,proto3" json:"name3,omitempty"`
	Name4 string `protobuf:"bytes,4,opt,name=name4,proto3" json:"name4,omitempty"`
	Name5 string `protobuf:"bytes,5,opt,name=name5,proto3" json:"name5,omitempty"`
}

func (x *ExampleMessageRequest) Reset() {
	*x = ExampleMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_example_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessageRequest) ProtoMessage() {}

func (x *ExampleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_example_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessageRequest.ProtoReflect.Descriptor instead.
func (*ExampleMessageRequest) Descriptor() ([]byte, []int) {
	return file_protoc_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleMessageRequest) GetName1() string {
	if x != nil {
		return x.Name1
	}
	return ""
}

func (x *ExampleMessageRequest) GetName2() string {
	if x != nil {
		return x.Name2
	}
	return ""
}

func (x *ExampleMessageRequest) GetName3() string {
	if x != nil {
		return x.Name3
	}
	return ""
}

func (x *ExampleMessageRequest) GetName4() string {
	if x != nil {
		return x.Name4
	}
	return ""
}

func (x *ExampleMessageRequest) GetName5() string {
	if x != nil {
		return x.Name5
	}
	return ""
}

var file_protoc_example_example_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "file.Topic",
		Tag:           "bytes,51234,opt,name=Topic",
		Filename:      "protoc/example/example.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string Topic = 51234;
	E_Topic = &file_protoc_example_example_proto_extTypes[0]
)

var File_protoc_example_example_proto protoreflect.FileDescriptor

var file_protoc_example_example_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x15, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x33,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x35, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x35, 0x3a, 0x0b, 0x92, 0x82,
	0x19, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x3a, 0x3a, 0x0a, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xa2, 0x90, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_example_example_proto_rawDescOnce sync.Once
	file_protoc_example_example_proto_rawDescData = file_protoc_example_example_proto_rawDesc
)

func file_protoc_example_example_proto_rawDescGZIP() []byte {
	file_protoc_example_example_proto_rawDescOnce.Do(func() {
		file_protoc_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_example_example_proto_rawDescData)
	})
	return file_protoc_example_example_proto_rawDescData
}

var file_protoc_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoc_example_example_proto_goTypes = []interface{}{
	(*ExampleMessageRequest)(nil),       // 0: file.ExampleMessageRequest
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_protoc_example_example_proto_depIdxs = []int32{
	1, // 0: file.Topic:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_example_example_proto_init() }
func file_protoc_example_example_proto_init() {
	if File_protoc_example_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_example_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_example_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protoc_example_example_proto_goTypes,
		DependencyIndexes: file_protoc_example_example_proto_depIdxs,
		MessageInfos:      file_protoc_example_example_proto_msgTypes,
		ExtensionInfos:    file_protoc_example_example_proto_extTypes,
	}.Build()
	File_protoc_example_example_proto = out.File
	file_protoc_example_example_proto_rawDesc = nil
	file_protoc_example_example_proto_goTypes = nil
	file_protoc_example_example_proto_depIdxs = nil
}
